region = "Global"             # "Global", "China"
flavor = "Retail"             # "Retail", "Classic", "Classic Era"
name = "iMorph Net"           # "iMorph", "iMorph Net", "iMorph Menu"
output_directory = "download" # Defaults to "download"
mega_get = "mega-get.bat"     # Path to the mega-get.bat from MEGAcmd. Defaults to "mega-get.bat".
api = "https://www.imorph.dev/api/apps" # URI to API. Defaults to "https://www.imorph.dev/api/apps".